### ISSUE TITLE
Bridge/repeater mode?

### ISSUE THREAD

**Issue by breandan** [cjimti/iotwifi#21]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [X] support request

* **Do you want to request a *feature* or report a *bug*?**

I have a question.

* **What is the current behavior?**

When I connect to the RPi running in AP+Station mode using my laptop, I cannot access the internet from the RPi, even though the RPi itself has access to the internet via station mode. I can ping `8.8.8.8` from the RPi and have no trouble reaching the internet when SSH'd into the RPi...

* **What is the expected behavior?**

I would like to be able to access the internet from a client connected over Wi-Fi using AP mode, when the RPi is connected to an internet enabled router. Is this possible, and if so, how?

**Comment by davidknezic** [comment]
This would make it possible to connect to a wifi with a captive portal. 👍

**Comment by cjimti** [comment]
I this would be a great addition. However, at the moment I only use it for IOT configuration, think Nest or Alexa, so I don't have a pressing need. It should be some simple rules for iptables. If you want work on it I would be happy to review any pull requests for inclusion. Otherwise, it will probably be another month before I can start working on this project again.

**Comment by davidknezic** [comment]
Fantastic, I'll look into this.

By the way, thank you for making `iotwifi`! It works perfectly and the instructions are exceptional. It only took me a couple of minutes to set it up and make my candy dispenser configurable! Great experience ✨

**Comment by breandan** [comment]
Duplicates #5, closing.
