### ISSUE TITLE
Raspberry Pi 3B+ support?

### ISSUE THREAD

**Issue by breandan** [cjimti/iotwifi#23]
Has anyone tried using this on the RPi 3B+ and experienced issues with intermittent or limited connectivity? Currently debugging some issues with the WiFi support and having difficulty establishing a stable connection on these boards. Thanks!

**Comment by breandan** [comment]
I think this might somehow be related to raspberrypi/linux#2453...

**Comment by cjimti** [comment]
I have about ~100 of them running on 3B+ and ~150 on 3B. I do get faulty wifi on some of them but have not noticed a difference in B and B+. About 3-5 of them were unable to connect until given a different access point. Since these units are run by non-technical people in various locations it has been difficult for me to determine why some access points are problematic. 

For the units that are stable (about 95% of them) they seem to remain that way for me. I have about 70 that have been online consistently for 6 months, sending data to my servers every 10 seconds. This is just my experience and there are a lot of different conditions.

**Comment by breandan** [comment]
Thanks for the feedback! To clarify, I am noticing connectivity issues between other devices and the RPi 3B+ in the access point configuration, not between the RPi and the router. Is this the same configuration you are running on the 3B+?

**Comment by cjimti** [comment]
I see... Yes, my devices only use AP for a short time after first boot to configure their connection to the router. I do notice that AP is unstable after a while but unclear what would be causing it. I'll take a deeper look at https://github.com/raspberrypi/linux/issues/2453 . Thanks for posting that.
